### ISSUE TITLE
neatmaps gives error 'heatmap' objects don't have these attributes: 'showlegend'

### ISSUE THREAD

**Issue by bharati-mehani** [cran/neatmaps#1]
Hi All, while using neatmaps with `consensusMap(neat_res)` or `neat_res$heatmap`, I am getting following error:

> 'heatmap' objects don't have these attributes: 'showlegend'
> Valid attributes include:
> 'type', 'visible', 'opacity', 'name', 'uid', 'ids', 'customdata', 'meta', 'hoverinfo', 'hoverlabel', 'stream', 'transforms', 'uirevision', 'z', 'x', 'x0', 'dx', 'y', 'y0', 'dy', 'text', 'hovertext', 'transpose', 'xtype', 'ytype', 'zsmooth', 'connectgaps', 'xgap', 'ygap', 'zhoverformat', 'hovertemplate', 'zauto', 'zmin', 'zmax', 'zmid', 'colorscale', 'autocolorscale', 'reversescale', 'showscale', 'colorbar', 'coloraxis', 'xcalendar', 'ycalendar', 'xaxis', 'yaxis', 'idssrc', 'customdatasrc', 'metasrc', 'hoverinfosrc', 'zsrc', 'xsrc', 'ysrc', 'textsrc', 'hovertextsrc', 'hovertemplatesrc', 'key', 'set', 'frame', 'transforms', '_isNestedKey', '_isSimpleKey', '_isGraticule', '_bbox'

Any help to solve this issue, will be highly appreciated.

Thanks

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!

**Comment by bharati16mehani** [comment]
Oh I missed it, Thank you for pointing this out.

**Comment by bharati-mehani** [comment]
Oh I missed it, Thank you for pointing this out.
